version: "3"

services:
  human_resource_db:
    platform: linux/x86_64
    container_name: human_resource_db
    image: mysql:5.7.30
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      app_net:
        ipv4_address: '172.40.0.2'

  backend:
    container_name: backend
    build: ./backend/
    image: backend
    command: bundle exec rails server -p 9001 -b 0.0.0.0
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - human_resource_db
    ports:
      - 9001:9001
    networks:
      app_net:
        ipv4_address: '172.40.0.3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/24

volumes:
  mysql_data:
  bundle_data:
